services:
  app:
    build:
      context: ./demo-pagos/
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      - DB_HOST=oracle-db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${ORACLE_PASSWORD}

  oracle-db:
    shm_size: 8g
    image:  container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db-container
    ports:
        - '9445:1521'
    environment:
      - ORACLE_ALLOW_REMOTE=${ORACLE_ALLOW_REMOTE}
      - ORACLE_DISABLE_ASYNCH_IO=${ORACLE_DISABLE_ASYNCH_IO}
      - ORACLE_PWD=${ORACLE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/${ORACLE_PASSWORD}@localhost:1521/XE"]
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - oracle-data:/u01/app/oracle
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  oracle-data: