services:
  app:
    build:
      context: ./demo-pagos/
      dockerfile: Dockerfile
    volumes:
      - maven-repo:/root/.m2
    container_name: app-container
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      - DB_HOST=oracle-db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${ORACLE_PASSWORD}

  oracle-db:
    shm_size: 8g
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db-container
    ports:
      - '1521:1521'
    environment:
      - ORACLE_ALLOW_REMOTE=${ORACLE_ALLOW_REMOTE}
      - ORACLE_DISABLE_ASYNCH_IO=${ORACLE_DISABLE_ASYNCH_IO}
      - ORACLE_PWD=${ORACLE_PASSWORD}
    healthcheck:
      test: [ "CMD", "/opt/oracle/checkDBStatus.sh"]
      interval: 2s
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./sql/:/opt/oracle/scripts/startup

volumes:
  oracle-data:
  maven-repo: